### ISSUE TITLE
Deprecation warning with Ruby 2.7

### ISSUE THREAD

**Issue by aried3r** [splitwise/super_diff#131]
I have a Rails model with a model spec that gives me a deprecation warnings using this gem.

Ruby 2.7.1 (I guess 2.7.2 and 2.7.3 also work when enabling deprecation warnings).
Rails 6.0
super_diff 0.8.0

```
super_diff-0.8.0/lib/super_diff/active_record/object_inspection/inspection_tree_builders/active_record_model.rb:30: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
super_diff-0.8.0/lib/super_diff/object_inspection/inspection_tree.rb:16: warning: The called method is defined here
```

The spec that causes this deprecation warnings is:

```Ruby
it { is_expected.to be_valid }
```

I'll see if I can create reproduction steps, but the model is an association and cannot simply be used as a standalone model, so it might take some time to exactly reproduce this, but perhaps this information is enough to find the warning.

Edit: Running `appraisal rails_6_0_rspec_gte_3_10 rspec --warnings` did not yield this warning.

PS: I had to edit `bin/setup` locally in my case, since while I do have `asdf` installed but am not using it for Ruby so the script quits early:

```console
$ bin/setup
No such plugin: ruby
== Installing Ruby 2.5.9 with asdf ==
No such plugin: ruby
```

After removing the check for `asdf` I also had to remove the check for `.tool-versions`, since I am using `rbenv` and the required Ruby version is found in `.ruby-version` (which contains a different version number than `.tool-versions` (2.7.1 vs 2.5.9)).

I'm only mentioning this, since I am not using a vanilla `bin/setup` but it should not affect my local testing.

**Comment by FunnyHector** [comment]
Bumping this up.

I'm having the same issue here. Can confirm this is an issue on Ruby 2.7.0 and 2.7.1, and when enabling deprecations (`RUBYOPT='-W:deprecated`) on 2.7.2 and later.

To reproduce:
Ruby version: 2.7.0/2.7.1. Or 2.7.2 and later versions, with ENV `RUBYOPT='-W:deprecated'`

```ruby
Person = Struct.new(:bar)

def foo(baz)
  baz << Person.new("bar")
end

let(:bar) { [] }

subject { foo(bar) }

it "raises deprecation warnings" do
  expect { subject }.to change { bar.first }.from(nil).to(have_attributes(bar: "bar"))
end
```

This emits the following warning:

```
DEPRECATION WARNING: /path_to_gems/super_diff-0.8.0/lib/super_diff/object_inspection/inspection_tree_builders/default_object.rb:46: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
 (called from block (3 levels) in <top (required)> at /path_to_test/test_spec.rb:12)
DEPRECATION WARNING: /path_to_gems/super_diff-0.8.0/lib/super_diff/object_inspection/inspection_tree.rb:16: warning: The called method is defined here
 (called from block (3 levels) in <top (required)> at /path_to_test/test_spec.rb:12)
```

These keyword args warnings are silenced in 2.7.2 and later 2.7.x versions, but it becomes error conditions straightaway on Ruby 3.

**Comment by mcmire** [comment]
I ran the example @FunnyHector gave (modified a bit to import `super_diff/rspec`) and it seemed to work on Ruby 3.2.1 without any issues. I've also tried generating a fresh Rails 7 app, adding a Person model, and then adding a test that just does `expect(Person.new).to have_attributes(foo: 'bar')`, and I'm not seeing any kind of errors either. So honestly, I'm not really sure how to reproduce these warnings. If anyone can create a repo that does this then I'd be really appreciative. I'm also planning on removing support for Ruby 2.7 fairly soon considering it just hit EOL. I know that doesn't solve the problem, but it does mean that this issue is stale, and I don't want to give the illusion that 2.7 will still be supported going forward. So I'm going to close it for now considering there are other things to fix, but again, if you can reproduce it, let me know and I will reopen this.
