### ISSUE TITLE
raise error when using custom matcher

### ISSUE THREAD

**Issue by masato-bkn** [splitwise/super_diff#163]
Hi, all. Thank you for developing a great gem. It could greatly improve my testing experience!

When I ran a test using this gem in my rails project, the title problem occurred.

```
NoMethodError:
undefined method `keys' for nil:NilClass

        keys = hash.keys
                    ^^^^^
```
[full backtrace is here](https://gist.github.com/masato-bkn/1f3bab217d2fbf1ad2bdd857800ddab7)

### test
```
# result          -> Hash class
# expected_result -> Array class
# resource        -> Active Model

it do
  expect(result).to match(
    'hoge' => expected_result.map do |resource|
      {
        'id' => 'foo',
        'url' => be_a_url,
      }
    end
  )
end
```

### custom matcher
```
RSpec::Matchers.define :be_a_url do
  match do |actual|
    actual =~ URI::DEFAULT_PARSER.make_regexp
  end
end
```

### environment
```
- Rails 7.0.4
- ruby 3.1.2
- RSpec 3.11
- super_diff 0.9.0
```

**Comment by mcmire** [comment]
@masato-bkn Thanks for reporting this, seems like a legit bug. I will look into this shortly!

**Comment by jk779** [comment]
I love this gem so much.

This happend to me multiple times now, my workaround was to un-include super_diff in rails_helper, which makes the problem in my application visible (rather from super_diff) and add it again after that, lol.

I'm using this, but I don't really think it matters whats the matchers logic, regarding the OPs matcher does something very different?

```ruby
RSpec::Matchers.define :include_or_eq do |expected|
  match do |actual|
    if actual.is_a?(Hash)
      return actual[:any].include? expected if actual.key? :any
      return actual[:all].sort == expected.sort if actual.key? :all

      raise 'Neither :all nor :any key defined :('
    else
      actual == expected
    end
  end
end
```

I've seen this in 

- rails 6.0, 6.1 and 7.0
- ruby 2.7 and 3.0
- rspec 3.x (currently 3.12.0)
- super_diff 0.9.0 at least, but i'm unsure if this already happened in 0.8

Here is a stack trace: https://gist.github.com/jk779/b7b3d321385c59f9a14b023d61b30447

If it helps, I can provide the code the matcher is used in, because maybe the usage of it is the problem, rather the existence of the matcher itself.

it goes along the lines of this (a helper for mocking authorizations, i'm sure it doesn't make much sense without context ;)

```ruby
ALL_ACTIONS = %i[read create delete update options].freeze

def mock_allow(subjects: [], actions: ALL_ACTIONS, return_user: false, return_value: true)
  if actions.present?
    subjects.each do |subject|
      actions.each do |action|
        allow(SomeClass)
          .to receive(:something)
            .with(
              anything,
              include_or_eq(subject),
              action,
              { return_user: return_user })
            .and_return return_value
      end
    end
  else
    subjects.each do |subject|
      allow(SomeClass).to(receive(:something).with(
        anything,
        include_or_eq(subject),
        anything,
        { return_user: anything })
      ) { SomeClass.raise_error(code: 403) }
    end
  end
end
```
