### ISSUE TITLE
super_diff seems to ignore --no-color

### ISSUE THREAD

**Issue by dgmstuart** [splitwise/super_diff#260]
In environments with no colors, it's important to be able to generate test output without color codes, otherwise the output looks like this:

```
|| Run options: include {:locations=>{"./spec/services/linked/url_builder_spec.rb"=>[17]}}
|| [31mF[0m
|| 
|| Failures:
|| 
||   1) Linked::UrlBuilder#booking_details_url returns a url for accessing a booking with token authentication
||      [1mFailure/Error: [0mexpect(token).to eq("no-a-real-id")
||        Expected [33m"not-a-real-id"[0m to eq [35m"no-a-real-id"[0m.
||      [36m# ./spec/services/linked/url_builder_spec.rb:21:in `block (3 levels) in <main>'[0m
||      [36m# ./spec/support/config/brand_filters.rb:47:in `block (3 levels) in <main>'[0m
```
...but it seems like after adding `super_diff`, we _always_ get color in the output, even when explicitly disabled by passing the `--no-color` flag to the `rspec` command.

**Comment by dgmstuart** [comment]
Is it because of this?

https://github.com/splitwise/super_diff/blob/2d06e39794ba1d43200693826d7fd4fa5d88b01c/lib/super_diff/core/configuration.rb#L187-L189

SuperDiff is working out whether colours should be used in its own way?
But RSpec already has its own ideas about whether colors should be used, and that isn't being taken into account?

**Comment by dgmstuart** [comment]
Patched in my `spec/rails_helper.rb`:

```ruby
RSpec.configure do |config|
  # ...
  
  SuperDiff.configure do |superdiff_config|
    superdiff_config.color_enabled = config.color_enabled?
  end
end
```

...but this feels like a bit of a hack?

The `SuperDiff` config needs to be inside the `RSpec` config block to ensure that `RSpec` is fully configured before we try to fetch the color settings from it?

**Comment by jas14** [comment]
@dgmstuart , thanks for submitting this issue. I agree that since SuperDiff is designed to work seamlessly with RSpec, it should adopt its configuration by default.

Since SuperDiff [can be used directly](https://splitwise.github.io/super_diff/releases/0.12.1/users/getting-started/#using-parts-of-superdiff-directly) without RSpec, we should make sure to preserve the default behavior when RSpec isn't loaded. But when RSpec _is_ loaded, we should use it if someone hasn't explicitly set `SuperDiff.configuration.color_enabled`.
