### ISSUE TITLE
Consider making ActiveRecord an optional dependency

### ISSUE THREAD

**Issue by flash-gordon** [splitwise/super_diff#58]
First of all, thank you for your work on this, it saves a lot of time. Things like this are what makes ruby different.

I updated deps of one of my AWS lambda functions and was surprised it now includes activerecord! I can see why super_diff has dedicated support for it, but I'm pretty sure it can be made opt-in, can't it? I have no plans using activerecord in this piece of code, and, moreover, I have no plans using activerecord anywhere, ROM FTW :)

Can you please consider moving activerecord out of runtime deps? I can definitely send a PR if needed.

**Comment by mcmire** [comment]
Hey! Sorry for the super late response on this. I've been on vacation, so I didn't see this before.

Yes, I think that makes sense to remove ActiveRecord as a dependency. Now that the gem uses Appraisal for testing, it seems like the `Appraisals` file would be an appropriate place to put that `gem` line so that we can at least keep testing against it. In addition, it might be better to say `gem "active_record", "> 4.2", "< 7.0"` in `lib/super_diff/active_record.rb` so that we can retain a dependency on the ActiveRecord version. What do you think about that?

**Comment by flash-gordon** [comment]
TBH I never tried appraisal but this sounds like a solid plan. 
I don't think adding `gem` to `lib/super_diff/active_record.rb` is a good idea, it should be done on the users' side. Instead, I would simply check if `ActiveRecord::VERSION::MAJOR` is defined and it's within the supported range. This is basically the same thing but doesn't do side effects. Do you want me to send a PR for that?

**Comment by mcmire** [comment]
Okay, adding a version check makes sense. I think technically Rails 4.2 is EOL now anyway so I guess we wouldn't need to get complicated with it. Go ahead and send a PR and I will take a look at it!
